# Generated by Django 3.2.9 on 2022-02-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='isimler',
            name='gorsel',
            field=models.FileField(blank=True, upload_to='kisi_gorsel/', verbose_name='Kişi Fotoğrafı'),
        ),
    ]
