# Generated by Django 3.2.9 on 2022-02-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0003_alter_isimler_gorsel'),
    ]

    operations = [
        migrations.AddField(
            model_name='isimler',
            name='text',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
