# Generated by Django 3.2.9 on 2022-02-24 18:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0004_isimler_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='isimler',
            name='aciklama',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
