# Generated by Django 3.2.9 on 2022-02-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0005_isimler_aciklama'),
    ]

    operations = [
        migrations.CreateModel(
            name='ornek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=40)),
                ('numara', models.IntegerField()),
            ],
        ),
    ]
