# Generated by Django 3.2.9 on 2022-03-03 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0007_auto_20220303_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='isimler',
            name='categori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anasayfa.kategori'),
        ),
    ]
